### ISSUE TITLE
[Demo] Request for demo on README

### ISSUE THREAD

**Issue by duynguyen-kun** [Ezmr7/addon-confluence#10]
Hi @Ezmr7 @joshrobertsv2 ,
I'm about to implement this addon for my storybook. Is there any way that I could see the demo of your addon? It's hard to imagine what the result would look like.

Thanks in advance

**Comment by joshrobertsv2** [comment]
@duynguyen-kun I added a screenshot of the final product. Is there any other info not covered that you would find useful? I should mention that currently it only works locally. Waiting for a response from the chromatic team on getting this into the hosted storybook

**Comment by joshrobertsv2** [comment]
Yes, we had to take a new approach since storybook doesn't have an api and only serves static pages. We opted to pre-fetch the documentation at build time, bundle it within the storybook-static directory. Please update and follow the new instructions in the read.me
