### ISSUE TITLE
addon-confluence v0.0.25 returns 404 in production environment

### ISSUE THREAD

**Issue by ivayloc** [Ezmr7/addon-confluence#12]
The `addon-confluence version 0.0.25` works correctly in the local development environment but returns a `404` status when deployed to the production environment. I suspect that the middleware might not be functioning properly in production.

**Environment:**

- Local Environment: Works as expected
- Production Environment: Returns 404 error
- Storybook Packages Installed:

  - @storybook/addon-designs: 7.0.9
  - @storybook/addon-essentials: 7.6.20
  - @storybook/addon-interactions: 7.6.20
  - @storybook/angular: 7.6.20
  - @storybook/core-server: 7.6.20
  - @storybook/jest: 0.2.3
  - @storybook/test: 8.1.4
  - @storybook/test-runner: 0.13.0
  - @storybook/testing-library: 0.2.2

**Steps to Reproduce:**

1. Deploy the application with `addon-confluence v0.0.25` to the production environment.
2. Attempt to make a request to `Confluence`.
3. Observe the `404` error response.

**Additional Information:**

- All necessary environment variables have been provided in the `.env` file.

**Comment by joshrobertsv2** [comment]
Yes, we had to take a new approach since storybook doesn't have an api and only serves static pages. We opted to pre-fetch the documentation at build time, bundle it within the storybook-static directory. Please update and follow the new instructions in the read.me
